name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: flask-tutorial-app-001
  PYTHON_VERSION: "3.11"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        python -m pytest --tb=short
    
    - name: Create artifact
      run: |
        zip -r flask-app.zip . -x "*.git*" "*__pycache__*" "*.pytest_cache*" "tests/*"
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: flask-app
        path: flask-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: flask-app

    - name: Unzip artifact
      run: unzip flask-app.zip

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: .
